version: '2.1'

services:
  flask-docker:
    image: flask-docker
    build: ./flask-docker
    environment: 
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - APP_SETTINGS=development
      - DATABASE_URL=postgres://postgres:postgres@user-db:5432/users_test
    ports:
      - 5000:5000
    depends_on: 
      - user-db
  
  user-db:
    image: db
    build: ./db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  task:
    image: task
    build: ./task
    container_name: schedule_task
  
  cronjobs:
    privileged: true
    image: mcuadros/ofelia:latest
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./cronjobs.ini:/etc/ofelia/config.ini

