version: '2.1'

services:
  flask-docker:
    image: flask-docker
    build: ./flask-docker
    environment: 
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - APP_SETTINGS=development
      - DATABASE_URL=postgres://postgres:postgres@user-db:5432/user_test
    ports:
      - 5000:5000
    depends_on: 
      - user-db
  
  user-db:
    image: db
    build: ./db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
